In [ ]:
1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
print(s)

Hi there Sam!


In [3]:
type(s)

str

In [4]:
s[1]

'i'

In [5]:
s[0]

'H'

In [6]:
s[1]

'i'

In [7]:
s[2]

' '

In [8]:
s[3]

't'

In [9]:
s[4]

'h'

In [10]:
s[5]

'e'

In [11]:
s[6]

'r'

In [12]:
s[7]

'e'

In [13]:
s[8]

' '

In [14]:
s[9]

'S'

In [15]:
s[10]

'a'

In [16]:
s[11]

'm'

In [17]:
s[12]

'!'

In [ ]:
2. Use .format() to print the following string.
Output should be: The diameter of Earth is 12742 kilometers.

In [18]:
txt="The diameter of {planet} is {diameter} kilometers".format(planet="Earth",diameter=12742)

In [19]:
print(txt)

The diameter of Earth is 12742 kilometers


In [ ]:
In this nest dictionary grab the word "hello"

In [2]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


In [11]:
import numpy as np

In [ ]:
4.1 Create an array of 10 zeros?

In [12]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
Create an array of 10 fives?

In [13]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
5. Create an array of all the even integers from 20 to 35

In [14]:
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array) 

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


In [ ]:
6. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
7. Concatinate a and b
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [48]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b), axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
8. Create a dataframe with 3 rows and 2 columns

In [53]:
import pandas as pd
import numpy as np
A = np.random.randint(10, size=(3,2))
df = pd.DataFrame(A)

In [54]:
df

0  1
0  9  8
1  3  1
2  0  6

In [ ]:
9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [4]:
import pandas as pd
  
per1 = pd.date_range(start ='1-1-2023', 
         end ='10-2-2023', freq ='M')
  
for val in per1:
    print(val)

2023-01-31 00:00:00
2023-02-28 00:00:00
2023-03-31 00:00:00
2023-04-30 00:00:00
2023-05-31 00:00:00
2023-06-30 00:00:00
2023-07-31 00:00:00
2023-08-31 00:00:00
2023-09-30 00:00:00


In [ ]:
10. Create 2D list to DataFrame
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [9]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns=['column 1', 'column 2','column 3']) 
print(df )

   column 1 column 2  column 3
0         1      aaa        22
1         2      bbb        25
2         3      ccc        24
